### ISSUE TITLE
0.4.17 seems to fail when attempting to run with python 2.7

### ISSUE THREAD

**Issue by aabes** [dcos/dcos-cli#1020]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

running CLI from source:

dcoscli.version=SNAPSHOT
dcos.version=1.9.0
dcos.commit=0ce03387884523f02624d3fb56c7fbe2e06e181b
dcos.bootstrap-id=58fd0833ce81b6244fc73bf65b5deb43217b0bd7

dcos-cli/cli) git status
On branch 0.4.17
nothing to commit, working tree clean

### What operating system and version are you using?
OSX 10.12.6

### What did you do?
If possible please provide a recipe for reproducing.

dcos node

### What did you expect to see?
list of nodes...

### What did you see instead?
dcos node
Traceback (most recent call last):
  File "/Users/aabes/venvs/dcos/bin/dcos", line 9, in <module>
    load_entry_point('dcoscli===SNAPSHOT', 'console_scripts', 'dcos')()
  File "/Users/aabes/venvs/dcos/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/aabes/venvs/dcos/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/aabes/venvs/dcos/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/aabes/venvs/dcos/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.12-x86_64/egg/dcoscli/main.py", line 9, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/dcos/cluster.py", line 7, in <module>
ImportError: No module named request

The stack trace occurs when using Python 2.7.13.
Note that if executed with python3 (Python 3.6.2) things work ok.

**Comment by klueska** [comment]
The CLi is only designed to work with python 3.5+

**Comment by ArmandGrillet** [comment]
We do not support the CLI 0.4.x anymore. If you are able to reproduce the issue following Kevin's comment with newer versions, please create a ticket on our public JIRA: https://jira.dcos.io/
