### ISSUE TITLE
TypeError when running dcos auth login inside virtualenv

### ISSUE THREAD

**Issue by frankscholten** [dcos/dcos-cli#1086]
### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

Commit ec9a048b92461ebe6f875feb61a117c09488cb21

### What operating system and version are you using?

Ubuntu 17.04

### What did you do?
If possible please provide a recipe for reproducing.

I followed the docs for creating virtualenvs and I started developing on the code. Then I ran `dcos auth login` and got this error:

```
(dcos-cli/cli) frank@frankcs ~/src/dcos-cli (cli/volume) $ dcos auth login
Traceback (most recent call last):
  File "/home/frank/src/dcos-cli/cli/dcoscli/subcommand.py", line 101, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/home/frank/src/dcos-cli/cli/dcoscli/auth/main.py", line 19, in main
    return _main(argv)
  File "/home/frank/src/dcos-cli/cli/dcoscli/util.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "/home/frank/src/dcos-cli/cli/dcoscli/auth/main.py", line 34, in _main
    return cmds.execute(_cmds(), args)
  File "/home/frank/src/dcos-cli/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/home/frank/src/dcos-cli/cli/dcoscli/auth/main.py", line 145, in _login
    _logout()
  File "/home/frank/src/dcos-cli/cli/dcoscli/auth/main.py", line 204, in _logout
    config.unset("core.dcos_acs_token")
  File "/home/frank/src/dcos-cli/dcos/config.py", line 366, in unset
    save(toml_config)
  File "/home/frank/src/dcos-cli/dcos/config.py", line 316, in save
    config_path = get_config_path()
  File "/home/frank/src/dcos-cli/dcos/config.py", line 112, in get_config_path
    return os.path.join(cluster_path, "dcos.toml")
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```
I stashed my changes and ran it again and I get the same error.

**Comment by philipnrmn** [comment]
Hi Frank,

I just ran through the same steps as you with the same commit hash and wasn't able to reproduce the issue. Can you delete (or temporarily move) your `~/.dcos` directory and retry, please?

**Comment by rgardler** [comment]
I got the same error but with a `dcos config set core.dcos_utl ...` command (yes I know it is deprecated, but I have tooling that uses it still).

Deleting `~/.dcos` resolved it for me.
