### ISSUE TITLE
KeyError: 'cmd', while running dcos marathon app list

### ISSUE THREAD

**Issue by f0ster** [dcos/dcos-cli#1138]
After auth'ing my client,
```
Ryans-MacBook-Pro:dcos user$ dcos --version && dcos marathon app list
dcoscli.version=0.4.15
dcos.version=1.10.0-rc1
dcos.commit=a5ecc9af5d9ca903f53fa16f6f0ebd597095652e
dcos.bootstrap-id=ff88379126df82559446b5916c769f562edb25d7
Traceback (most recent call last):
  File "cli/dcoscli/subcommand.py", line 101, in run_and_capture
  File "cli/dcoscli/marathon/main.py", line 23, in main
  File "cli/dcoscli/util.py", line 22, in wrapper
  File "cli/dcoscli/marathon/main.py", line 36, in _main
  File "dcos/cmds.py", line 43, in execute
  File "cli/dcoscli/marathon/main.py", line 401, in list
  File "cli/dcoscli/tables.py", line 115, in app_table
  File "cli/dcoscli/tables.py", line 923, in table
  File "cli/dcoscli/tables.py", line 923, in <listcomp>
  File "cli/dcoscli/tables.py", line 65, in get_cmd
KeyError: 'cmd'
```

**Comment by bamarni** [comment]
Hi @f0ster ,

The CLI your using is quite old, could you try with the one for 1.10 clusters? (https://downloads.dcos.io/binaries/cli/darwin/x86-64/dcos-1.10/dcos)

**Comment by ArmandGrillet** [comment]
This should be fixed by now, @f0ster please create a ticket in https://jira.dcos.io/ regarding the `dcos-cli` component if that's not the case.
