### ISSUE TITLE
dcos job kill: Attribute error in normalize_marathon_id_path

### ISSUE THREAD

**Issue by niroyb** [dcos/dcos-cli#1139]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

```C:\Users\niroy>dcos --version
dcoscli.version=0.5.7
dcos.version=1.9.0
dcos.commit=0ce03387884523f02624d3fb56c7fbe2e06e181b
dcos.bootstrap-id=58fd0833ce81b6244fc73bf65b5deb43217b0bd7```
```

### What operating system and version are you using?
Windows 10 build 1703

### What did you do?
I create a simple job and schedule, let it run then tried to kill kill the job.

```
dcos job show sleep2
{
  "id": "sleep2",
  "labels": {},
  "run": {
    "artifacts": [],
    "cmd": "echo \"Hello world\"\ndate\nsleep 1000\necho \"Bye\"\n",
    "cpus": 0.01,
    "disk": 0,
    "env": {},
    "maxLaunchDelay": 3600,
    "mem": 32,
    "placement": {
      "constraints": []
    },
    "restart": {
      "policy": "NEVER"
    },
    "volumes": []
  }
}

dcos job schedule show sleep2 --json
[
  {
    "concurrencyPolicy": "ALLOW",
    "cron": "*/5 * * * *",
    "enabled": true,
    "id": "default",
    "nextRunAt": "2018-01-26T23:10:00.000+0000",
    "startingDeadlineSeconds": 900,
    "timezone": "UTC"
  }
]
```

### What did you expect to see?
Job gets killed

### What did you see instead?

```
dcos job kill sleep2
Traceback (most recent call last):
  File "dcoscli\subcommand.py", line 103, in run_and_capture
  File "dcoscli\job\main.py", line 40, in main
  File "dcoscli\util.py", line 24, in wrapper
  File "dcoscli\job\main.py", line 61, in _main
  File "dcos\cmds.py", line 43, in execute
  File "dcoscli\job\main.py", line 247, in _kill
  File "dcos\metronome.py", line 343, in kill_run
  File "dcos\util.py", line 730, in normalize_marathon_id_path
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by bamarni** [comment]
I could reproduce this, @kensipe any idea?

**Comment by Kira-Lappo** [comment]
I got the same issue but with ```dcos job kill job-id --all```
