### ISSUE TITLE
dcos package install --cli is not working

### ISSUE THREAD

**Issue by bergerx** [dcos/dcos-cli#1190]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

```
[dcos-sandbox]~ $ dcos --version
dcoscli.version=0.6.0
dcos.version=1.11.0
dcos.commit=b6d6ad4722600877fde2860122f870031d109da3
dcos.bootstrap-id=a0654657903fb68dff60f6e522a7f241c1bfbf0f
[dcos-sandbox]~ $ 
```

### What operating system and version are you using?
osx

### What did you do?

```
[dcos-sandbox]~ $ dcos package install elastic --cli --yes
By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Installing CLI subcommand for package [elastic] version [2.2.0-5.6.5]
URL [http://admin.<cropped>.io/package/resource?url=https://downloads.mesosphere.com/elastic/assets/2.2.0-5.6.5/dcos-service-cli-darwin] is unreachable.
[dcos-sandbox]~ $ 
```

### What did you expect to see?
I was expecting the cli package to be installed.

**Comment by bamarni** [comment]
What version of macOS are you using, and when did you download the CLI? We pushed a new artifact a few days ago based on this change : https://github.com/dcos/dcos-cli/commit/6cf8ca4e011160310fdfe8c75bc9130e435f198a

Basically, from PyInstaller : `PyInstaller builds apps that are compatible with the Mac OS X release
  in which you run it, and following releases.`

**Comment by bergerx** [comment]
I'm on macOS Sierra, but the same issue happens everyone in our team, I suspect that this is because due to some setup in our clusters, but I have no clue.

The same issue happens also on linux laptops:

```
[tom@tb ~]$ dcos package install elastic --cli --yes
By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Installing CLI subcommand for package [elastic] version [2.2.0-5.6.5]
URL [http://admin.<cropped>.io/package/resource?url=https://downloads.mesosphere.com/elastic/assets/2.2.0-5.6.5/dcos-service-cli-linux] is unreachable.
```

**Comment by bergerx** [comment]
I asked the team to run the command, seems like it worked on high sierra as expected:

```
$ dcos package install elastic --cli --yes
By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Installing CLI subcommand for package [elastic] version [2.2.0-5.6.5]
New command available: dcos elastic
```

**Comment by bamarni** [comment]
Could you show the output of the command with --debug and --log-level=debug? And the sha256sum of the binary please?

**Comment by bergerx** [comment]
```
[dcos-sandbox]~ $ type dcos
dcos is hashed (/usr/local/bin/dcos)
[dcos-sandbox]~ $ shasum -a 256 /usr/local/bin/dcos
3ca01b0f8f8eb713603f4ae64637aa9fb620f89e810cc9c2d6602ae790242c02  /usr/local/bin/dcos
[dcos-sandbox]~ $ 
```

```
[dcos-sandbox]~ $ dcos --debug --log-level=DEBUG  package install elastic --cli --yes 2>&1 | sed 's/admin\..*\.io/admin.<cropped>.io/' 
MainThread: 2018-03-29 11:13:11,763 dcos/http.py:_request:163 - Sending HTTP ['get'] to ['https://admin.<cropped>.io/capabilities']: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1'}
MainThread: 2018-03-29 11:13:11,770 urllib3/connectionpool.py:_new_conn:824 - Starting new HTTPS connection (1): admin.<cropped>.io
MainThread: 2018-03-29 11:13:12,724 urllib3/connectionpool.py:_make_request:396 - https://admin.<cropped>.io:443 "GET /capabilities HTTP/1.1" 200 144
MainThread: 2018-03-29 11:13:12,727 dcos/http.py:_request:193 - Received HTTP response [200]: {'Connection': 'keep-alive', 'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Server': 'openresty', 'Date': 'Thu, 29 Mar 2018 10:13:12 GMT', 'Content-Length': '144'}
MainThread: 2018-03-29 11:13:12,727 dcos/util.py:timer:609 - duration: dcos.http._request: 0.96s
MainThread: 2018-03-29 11:13:12,734 dcos/http.py:_request:163 - Sending HTTP ['post'] to ['https://admin.<cropped>.io/package/describe']: {'Content-Type': 'application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v3'}
MainThread: 2018-03-29 11:13:12,736 urllib3/connectionpool.py:_new_conn:824 - Starting new HTTPS connection (1): admin.<cropped>.io
MainThread: 2018-03-29 11:13:16,039 urllib3/connectionpool.py:_make_request:396 - https://admin.<cropped>.io:443 "POST /package/describe HTTP/1.1" 200 69945
MainThread: 2018-03-29 11:13:16,154 dcos/http.py:_request:193 - Received HTTP response [200]: {'Connection': 'keep-alive', 'Content-Type': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v3', 'Server': 'openresty', 'Date': 'Thu, 29 Mar 2018 10:13:15 GMT', 'Content-Length': '69945'}
MainThread: 2018-03-29 11:13:16,154 dcos/util.py:timer:609 - duration: dcos.http._request: 3.42s
send: b'GET /capabilities HTTP/1.1\r\nHost: admin.<cropped>.io\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: python-requests/2.18.4\r\nAccept: application/vnd.dcos.capabilities+json;charset=utf-8;version=v1\r\nConnection: keep-alive\r\nContent-Type: application/vnd.dcos.capabilities+json;charset=utf-8;version=v1\r\nAuthorization: token=eyJhbGciOiJIUzI1NiIsImtpZCI6InNlY3JldCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIzeUY1VE9TemRsSTQ1UTF4c3B4emVvR0JlOWZOeG05bSIsImVtYWlsIjoiYmVraXJkb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNTIyNzQ5OTE3LCJpYXQiOjE1MjIzMTc5MTcsImlzcyI6Imh0dHBzOi8vZGNvcy5hdXRoMC5jb20vIiwic3ViIjoiZ2l0aHVifDQ1NTMxIiwidWlkIjoiYmVraXJkb0BnbWFpbC5jb20ifQ.G4sHaYxp-cq2M-NvGbChyuvp-ZS3WbvAG3SzaYB8dcM\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type header: Date header: Server header: Content-Length header: Connection send: b'POST /package/describe HTTP/1.1\r\nHost: admin.<cropped>.io\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: python-requests/2.18.4\r\nAccept: application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v3\r\nConnection: keep-alive\r\nContent-Type: application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1\r\nContent-Length: 26\r\nAuthorization: token=eyJhbGciOiJIUzI1NiIsImtpZCI6InNlY3JldCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIzeUY1VE9TemRsSTQ1UTF4c3B4emVvR0JlOWZOeG05bSIsImVtYWlsIjoiYmVraXJkb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNTIyNzQ5OTE3LCJpYXQiOjE1MjIzMTc5MTcsImlzcyI6Imh0dHBzOi8vZGNvcy5hdXRoMC5jb20vIiwic3ViIjoiZ2l0aHVifDQ1NTMxIiwidWlkIjoiYmVraXJkb0BnbWFpbC5jb20ifQ.G4sHaYxp-cq2M-NvGbChyuvp-ZS3WbvAG3SzaYB8dcM\r\n\r\n'
send: b'{"packageName": "elastic"}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type header: Date header: Server header: Content-Length header: Connection By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Installing CLI subcommand for package [elastic] version [2.2.0-5.6.5]
MainThread: 2018-03-29 11:13:16,162 dcos/util.py:ensure_dir_exists:203 - Creating directory: '/Users/bdogan/.dcos/clusters/05305b03-55ab-405b-b745-41dbeee09b6a/subcommands/elastic'
MainThread: 2018-03-29 11:13:16,182 dcos/http.py:_request:163 - Sending HTTP ['get'] to ['http://admin.<cropped>.io/package/resource?url=https://downloads.mesosphere.com/elastic/assets/2.2.0-5.6.5/dcos-service-cli-darwin']: {'Accept': 'application/json'}
MainThread: 2018-03-29 11:13:16,186 urllib3/connectionpool.py:_new_conn:208 - Starting new HTTP connection (1): admin.<cropped>.io
MainThread: 2018-03-29 11:13:16,393 dcos/http.py:_request:182 - HTTP Connection Error
Traceback (most recent call last):
  File "urllib3/connection.py", line 141, in _new_conn
  File "urllib3/util/connection.py", line 83, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 601, in urlopen
  File "urllib3/connectionpool.py", line 357, in _make_request
  File "http/client.py", line 1107, in request
  File "http/client.py", line 1152, in _send_request
  File "http/client.py", line 1103, in endheaders
  File "http/client.py", line 934, in _send_output
  File "http/client.py", line 877, in send
  File "urllib3/connection.py", line 166, in connect
  File "urllib3/connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10ae6b0f0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 440, in send
  File "urllib3/connectionpool.py", line 639, in urlopen
  File "urllib3/util/retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='admin.<cropped>.io', port=80): Max retries exceeded with url: /package/resource?url=https://downloads.mesosphere.com/elastic/assets/2.2.0-5.6.5/dcos-service-cli-darwin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ae6b0f0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dcos/http.py", line 172, in _request
  File "requests/api.py", line 58, in request
  File "requests/sessions.py", line 508, in request
  File "requests/sessions.py", line 618, in send
  File "requests/adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='admin.<cropped>.io', port=80): Max retries exceeded with url: /package/resource?url=https://downloads.mesosphere.com/elastic/assets/2.2.0-5.6.5/dcos-service-cli-darwin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ae6b0f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
MainThread: 2018-03-29 11:13:16,396 dcos/util.py:timer:609 - duration: dcos.http._request: 0.21s
URL [http://admin.<cropped>.io/package/resource?url=https://downloads.mesosphere.com/elastic/assets/2.2.0-5.6.5/dcos-service-cli-darwin] is unreachable.
[dcos-sandbox]~ $ 
```

**Comment by bergerx** [comment]
The issue seems to be forcing the protocol, we only have https enabled to reach the DCOS UI, but when dcos-cli want to download it seems to be enforcing http rather.

**Comment by addisonj** [comment]
I also have this issue after upgrading to dcos 1.11 and dcoscli 0.6.0. We lock down the only allow https URLs and am now unable to install packages via the CLI

In my case, running on linux

**Comment by bamarni** [comment]
cc @takirala @jsancio

**Comment by addisonj** [comment]
I dug in a little deeper... thought maybe I could maybe patch this in the CLI, but it is coming back from cosmos with these URLs encoded in the package description.

It looks like https://github.com/dcos/cosmos/pull/676 adds this, specifically the call to `pkg.rewrite`. I am still digging in to see where it determines the host URL as it appears to pull the uri schema from that config... which might make it possible to fix this locally in dcos if enforcing https

**Comment by addisonj** [comment]
Ooookay, I think I know everything going on here... 

With the cosmos changes above, this breaks when only https is open AND SSL termination is done in front of adminrouter. 

Cosmos uses the x-forwarded-proto or x-url-scheme headers to determine what proto to rewrite URLs too. As cosmos is usually fronted by adminrouter and adminrouter sets x-forwarded-proto, this would be correct. 

However, adminrouter doesn't respect x-forwarded-proto itself, it just uses the `$schema` variable. So in situations like in AWS where you are doing SSL termination at an ELB and redirecting to the HTTP endpoint of adminrouter, adminrouter sets x-forwarded-proto to http.

I tried hacking in `X-Url-Scheme` to dcos-cli, but that doesn't appear to work either as adminrouter isn't set up to forward the header as it explicitly sets ` proxy_pass_request_headers off`.

The cleanest fix here would be to make adminrouter do something like this:

```
diff --git a/packages/adminrouter/extra/src/includes/proxy-headers.conf b/packages/adminrouter/extra/src/includes/proxy-headers.conf
index df75bc5d..947da647 100644
--- a/packages/adminrouter/extra/src/includes/proxy-headers.conf
+++ b/packages/adminrouter/extra/src/includes/proxy-headers.conf
@@ -1,4 +1,8 @@
 proxy_set_header Host $http_host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
-proxy_set_header X-Forwarded-Proto $scheme;
+if ($http_x_forwarded_proto) {
+  proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
+} else {
+  proxy_set_header X-Forwarded-Proto $scheme;
+}
```

For now... I think I might just hit dcos directly via a VPN...

Would be nice to get a fix for this though as I imagine it isn't totally uncommon to use an ELB to do SSL termination

**Comment by bamarni** [comment]
Thanks @addisonj for investigating. I've forwarded your findings internally, we are currently actively looking into this issue. I'll keep you updated.
