### ISSUE TITLE
dcos-cli does not install on arch

### ISSUE THREAD

**Issue by sttts** [dcos/dcos-cli#386]
```
$ docker run -it base/archlinux /bin/bash
$ pacman -Syu
$ pacman -S python-virtualenv python-pip
$ mkdir -p dcos && cd dcos && \
curl -O https://downloads.mesosphere.io/dcos-cli/install.sh && \
bash ./install.sh . http://pool-5d44-elasticl-i3e25g6agoox-1339750650.us-west-2.elb.amazonaws.com && \
source ./bin/env-setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3654  100  3654    0     0  14963      0 --:--:-- --:--:-- --:--:-- 14975
Traceback (most recent call last):
  File "/usr/sbin/pip", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.5/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.5/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.5/site-packages/pip/wheel.py", line 35, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distlib/compat.py", line 66, in <module>
    from urllib.request import (urlopen, urlretrieve, Request, url2pathname,
ImportError: cannot import name 'HTTPSHandler'
```

**Comment by jsancio** [comment]
Looks like a bug with pip. Probably a really old version. Can you try `sudo
pip install -U virtualenv pip`?

**Comment by sttts** [comment]
Only did the 4 commands listed above, just replay them locally.

**Comment by jsancio** [comment]
Okay, thanks!

**Comment by tamarrow** [comment]
The binary cli makes this install easier, and works great on arch: 
<img width="722" alt="screen shot 2016-07-26 at 2 43 38 pm" src="https://cloud.githubusercontent.com/assets/1292768/17156612/9cd71092-533f-11e6-8d05-fa8a4d7e51d2.png">
