### ISSUE TITLE
dcos task log does not handle unicode

### ISSUE THREAD

**Issue by jtwarren** [dcos/dcos-cli#621]
The emitter is not handling unicode and unfortunately my logs contain unicode characters that are non-trivial to remove.  

https://github.com/dcos/dcos-cli/blob/master/dcos/emitting.py#L163

```python
>>> text = u"dcos"
>>> str(text)
'dcos'
>>> text = u"dcõs"
>>> str(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf5' in position 2: ordinal not in range(128)
```

### What version of the DCOS CLI are you using (`dcos --version`)?
dcos version 0.4.4

### What version of DCOS are you using?
N/A

### What operating system and version are you using?
OSX 10.11.3

### What did you do?
If possible please provide a recipe for reproducing.
`dcos task log --follow`

### What did you expect to see?
Valid log output

### What did you see instead?
```
Traceback (most recent call last):
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/subcommand.py", line 96, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/task/main.py", line 17, in main
    return _main(argv)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/util.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/task/main.py", line 30, in _main
    return cmds.execute(_cmds(), args)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/task/main.py", line 157, in _log
    log.log_files(mesos_files, follow, lines)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/log.py", line 43, in log_files
    mesos_files)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/log.py", line 93, in _stream_files
    lines)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcoscli/log.py", line 118, in _output
    emitter.publish(line)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcos/emitting.py", line 57, in publish
    self._handler(event)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcos/emitting.py", line 74, in print_handler
    _page(event, pager_command)
  File "/Users/jtwarren/Wellframe/dcos/lib/python2.7/site-packages/dcos/emitting.py", line 163, in _page
    output = str(output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 536: ordinal not in range(128)
```

**Comment by jsancio** [comment]
Thanks. Looking into it.
