### ISSUE TITLE
Cannot install dcos spark cli with DC/OS 1.8

### ISSUE THREAD

**Issue by martinstuder** [dcos/dcos-cli#708]
### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

DC/OS 1.8 using AWS CloudFormation template from https://dcos.io/docs/1.8/administration/installing/cloud/aws/

DC/OS CLI:
dcoscli.version=0.4.10
dcos.version=N/A
dcos.commit=N/A
dcos.bootstrap-id=N/A
### What operating system and version are you using?

Ubuntu 16.04.01 LTS
### What did you do?

```
dcos --log-level=DEBUG package install spark --cli
```
### What did you expect to see?

Spark on DC/OS was installed via the Web UI from the universe. I expected that I can install the DC/OS spark CLI afterwards, which used to work with DC/OS 1.7 and the previous version of the DC/OS CLI.
### What did you see instead?

```
mstuder@falcon:~/dcos$ dcos --log-level=DEBUG package install spark --cli
MainThread: 2016-08-08 21:01:31,441 dcos/http.py:_request:87 - Sending HTTP ['get'] to ['http://dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com/capabilities']: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1'}
MainThread: 2016-08-08 21:01:31,448 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-08 21:01:31,599 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "GET /capabilities HTTP/1.1" 200 82
MainThread: 2016-08-08 21:01:31,601 dcos/http.py:_request:117 - Received HTTP response [200]: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Server': 'openresty/1.9.15.1', 'Connection': 'keep-alive', 'Content-Length': '82', 'Date': 'Mon, 08 Aug 2016 19:01:31 GMT'}
MainThread: 2016-08-08 21:01:31,601 dcos/util.py:timer:529 - duration: dcos.http._request: 0.16s
MainThread: 2016-08-08 21:01:31,602 dcos/http.py:_request:87 - Sending HTTP ['post'] to ['http://dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com/package/describe']: {'Content-Type': 'application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2'}
MainThread: 2016-08-08 21:01:31,604 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-08 21:01:31,755 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "POST /package/describe HTTP/1.1" 200 13068
MainThread: 2016-08-08 21:01:31,815 dcos/http.py:_request:117 - Received HTTP response [200]: {'Content-Type': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2', 'Server': 'openresty/1.9.15.1', 'Connection': 'keep-alive', 'Content-Length': '13068', 'Date': 'Mon, 08 Aug 2016 19:01:31 GMT'}
MainThread: 2016-08-08 21:01:31,815 dcos/util.py:timer:529 - duration: dcos.http._request: 0.21s
Installing CLI subcommand for package [spark] version [1.0.1-2.0.0]
MainThread: 2016-08-08 21:01:31,816 dcos/util.py:ensure_dir_exists:129 - Creating directory: '/home/mstuder/.dcos/subcommands/spark'
MainThread: 2016-08-08 21:01:31,817 dcos/subcommand.py:_execute_command:571 - Calling: ['/usr/local/bin/virtualenv', '--version']
MainThread: 2016-08-08 21:01:31,859 dcos/subcommand.py:_execute_command:584 - Command script's stdout: b'15.0.2\n'
MainThread: 2016-08-08 21:01:31,860 dcos/subcommand.py:_execute_command:585 - Command script's stderr: b''
MainThread: 2016-08-08 21:01:31,860 dcos/subcommand.py:_execute_command:571 - Calling: ['/usr/local/bin/virtualenv', '/home/mstuder/.dcos/subcommands/spark/env']
MainThread: 2016-08-08 21:01:32,658 dcos/subcommand.py:_execute_command:581 - Command script's stdout: b'New python executable in /home/mstuder/.dcos/subcommands/spark/env/bin/python\nInstalling setuptools, pip, wheel...\n  Complete output from command /home/mstuder/.dcos/...spark/env/bin/python - setuptools pip wheel:\n  Traceback (most recent call last):\n  File "<stdin>", line 7, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/index.py", line 30, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 31, in <module>\nImportError: cannot import name HTTPSHandler\n----------------------------------------\n...Installing setuptools, pip, wheel...done.\n'
MainThread: 2016-08-08 21:01:32,658 dcos/subcommand.py:_execute_command:582 - Command script's stderr: b'Traceback (most recent call last):\n  File "/usr/local/bin/virtualenv", line 11, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main\n    symlink=options.symlink)\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 944, in create_environment\n    download=download,\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 900, in install_wheel\n    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 795, in call_subprocess\n    % (cmd_desc, proc.returncode))\nOSError: Command /home/mstuder/.dcos/...spark/env/bin/python - setuptools pip wheel failed with error code 1\n'
Error installing 'spark' package.
Run with `dcos --log-level=ERROR` to see the full output.
```

**Comment by martinstuder** [comment]
As suggested by @mgummelt  this issue was moved here from https://github.com/mesosphere/dcos-spark/issues/35

**Comment by jsancio** [comment]
@martinstuder Can you run `dcos --log-level=debug --version` against and include the `dcos...` version information? The version of DC/OS you are using is important.

@tamarrow @mgummelt, I see from the logs that we are trying to install the spark CLI using `pip`. Shouldn't we be trying to install using the native CLI packaging?

**Comment by jsancio** [comment]
@martinstuder Can you run `dcos --log-level=debug --version` against and include the `dcos...` version information? The version of DC/OS you are using is important.

@tamarrow @mgummelt, I see from the logs that we are trying to install the spark CLI using `pip`. Shouldn't we be trying to install using the native CLI packaging?

**Comment by martinstuder** [comment]
@jsancio I was running the above against DC/OS 1.8 but re-ran the same against the newer DC/OS 1.8.1 AWS CloudFormation template:

```
dcos --log-level=DEBUG --version package install spark --cli
MainThread: 2016-08-15 20:02:40,724 dcos/http.py:_request:87 - Sending HTTP ['get'] to ['http://dcos-elasticloadba-17q7kqx0oopde-1788100312.eu-central-1.elb.amazonaws.com/dcos-metadata/dcos-version.json']: {'Accept': 'application/json'}
MainThread: 2016-08-15 20:02:40,729 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-17q7kqx0oopde-1788100312.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-15 20:02:40,876 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "GET /dcos-metadata/dcos-version.json HTTP/1.1" 200 154
MainThread: 2016-08-15 20:02:40,877 dcos/http.py:_request:117 - Received HTTP response [200]: {'Accept-Ranges': 'bytes', 'Server': 'openresty/1.9.15.1', 'Date': 'Mon, 15 Aug 2016 18:02:40 GMT', 'Content-Length': '154', 'Last-Modified': 'Thu, 11 Aug 2016 01:33:48 GMT', 'ETag': '"57abd5fc-9a"', 'Content-Type': 'application/json', 'Connection': 'keep-alive'}
MainThread: 2016-08-15 20:02:40,877 dcos/util.py:timer:529 - duration: dcos.http._request: 0.15s
dcoscli.version=0.4.10
dcos.version=1.8.1
dcos.commit=c1915a9f9f02caf7e34022eaea04f15ff853bd0e
dcos.bootstrap-id=aab1123cef197db2d94bd8ba024c63a99b876958
```

```
dcos --log-level=debug package install spark --cli
MainThread: 2016-08-15 20:04:29,713 dcos/http.py:_request:87 - Sending HTTP ['get'] to ['http://dcos-elasticloadba-17q7kqx0oopde-1788100312.eu-central-1.elb.amazonaws.com/capabilities']: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1'}
MainThread: 2016-08-15 20:04:29,718 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-17q7kqx0oopde-1788100312.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-15 20:04:29,853 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "GET /capabilities HTTP/1.1" 200 103
MainThread: 2016-08-15 20:04:29,854 dcos/http.py:_request:117 - Received HTTP response [200]: {'Date': 'Mon, 15 Aug 2016 18:04:29 GMT', 'Connection': 'keep-alive', 'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Server': 'openresty/1.9.15.1', 'Content-Length': '103'}
MainThread: 2016-08-15 20:04:29,854 dcos/util.py:timer:529 - duration: dcos.http._request: 0.14s
MainThread: 2016-08-15 20:04:29,855 dcos/http.py:_request:87 - Sending HTTP ['post'] to ['http://dcos-elasticloadba-17q7kqx0oopde-1788100312.eu-central-1.elb.amazonaws.com/package/describe']: {'Content-Type': 'application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2'}
MainThread: 2016-08-15 20:04:29,856 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-17q7kqx0oopde-1788100312.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-15 20:04:29,985 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "POST /package/describe HTTP/1.1" 200 13003
MainThread: 2016-08-15 20:04:29,986 dcos/http.py:_request:117 - Received HTTP response [200]: {'Date': 'Mon, 15 Aug 2016 18:04:29 GMT', 'Connection': 'keep-alive', 'Content-Type': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2', 'Server': 'openresty/1.9.15.1', 'Content-Length': '13003'}
MainThread: 2016-08-15 20:04:29,986 dcos/util.py:timer:529 - duration: dcos.http._request: 0.13s
Installing CLI subcommand for package [spark] version [1.0.1-2.0.0]
MainThread: 2016-08-15 20:04:29,987 dcos/util.py:ensure_dir_exists:129 - Creating directory: '/root/.dcos/subcommands/spark'
MainThread: 2016-08-15 20:04:29,988 dcos/subcommand.py:_execute_command:571 - Calling: ['/usr/local/bin/virtualenv', '--version']
MainThread: 2016-08-15 20:04:30,031 dcos/subcommand.py:_execute_command:584 - Command script's stdout: b'15.0.2\n'
MainThread: 2016-08-15 20:04:30,032 dcos/subcommand.py:_execute_command:585 - Command script's stderr: b''
MainThread: 2016-08-15 20:04:30,032 dcos/subcommand.py:_execute_command:571 - Calling: ['/usr/local/bin/virtualenv', '/root/.dcos/subcommands/spark/env']
MainThread: 2016-08-15 20:04:30,713 dcos/subcommand.py:_execute_command:581 - Command script's stdout: b'New python executable in /root/.dcos/subcommands/spark/env/bin/python\nInstalling setuptools, pip, wheel...\n  Complete output from command /root/.dcos/subcommands/spark/env/bin/python - setuptools pip wheel:\n  Traceback (most recent call last):\n  File "<stdin>", line 7, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/index.py", line 30, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 31, in <module>\nImportError: cannot import name HTTPSHandler\n----------------------------------------\n...Installing setuptools, pip, wheel...done.\n'
MainThread: 2016-08-15 20:04:30,713 dcos/subcommand.py:_execute_command:582 - Command script's stderr: b'Traceback (most recent call last):\n  File "/usr/local/bin/virtualenv", line 11, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main\n    symlink=options.symlink)\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 944, in create_environment\n    download=download,\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 900, in install_wheel\n    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 795, in call_subprocess\n    % (cmd_desc, proc.returncode))\nOSError: Command /root/.dcos/subcommands/spark/env/bin/python - setuptools pip wheel failed with error code 1\n'
Error installing 'spark' package.
Run with `dcos --log-level=ERROR` to see the full output.
```

**Comment by martinstuder** [comment]
I actually get the same problem when trying to install the kafka subcommand. The cassandra one works though.

**Comment by gasparms** [comment]
Same problem when I try to install spark cli.

**Comment by sdechi** [comment]
Same here with Azure and the subcommands for Spark / Kafka but for me the cassandra command is also broken.

dcoscli.version=0.4.10
dcos.version=1.8.3

**Comment by ArmandGrillet** [comment]
We now only support DC/OS >= 1.10 and thus the CLI >= 0.5. Sorry that this issue was not resolved back in 2017, I have not heard of that bug recently and I suggest you to follow https://docs.mesosphere.com/services/spark/v1.1.1-2.2.0/install/ to install the Spark CLI.
