### ISSUE TITLE
dcos cli ssl CERTIFICATE_VERIFY_FAILED when accessing kafka connection

### ISSUE THREAD

**Issue by BenjaminTrapani** [dcos/dcos-cli#711]
### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

dcos --version
dcoscli.version=0.4.10
dcos.version=1.7-open
dcos.commit=14509fe1e7899f439527fb39867194c7a425c771
dcos.bootstrap-id=3a2b7e03c45cd615da8dfb1b103943894652cd71

### What operating system and version are you using?

I am running DCOS on MacOS 10.11.6 with Vagrant and virtualbox (virtualbox version 5.0.26 r108824)

### What did you do?
If possible please provide a recipe for reproducing.

dcos kafka connection

### What did you expect to see?

Expected to see the following, available after authentication in a web browser: 
{"address":["192.168.65.121:9220"],"zookeeper":"master.mesos:2181/dcos-service-kafka","dns":["broker-0.kafka.mesos:9220"]}

### What did you see instead?

No handlers could be found for logger "dcos.http"
Traceback (most recent call last):
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/bin/dcos-kafka", line 11, in <module>
    sys.exit(main())
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos_kafka/cli.py", line 257, in main
    cli(obj={})
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos_kafka/cli.py", line 67, in connection
    cluster_api.connection()
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos_kafka/cluster_api.py", line 19, in connection
    ku.http_get_json("/connection")
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos_kafka/kafka_utils.py", line 48, in http_get_json
    'get', slash_command, params, ignored_errors=ignored_errors)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos_kafka/kafka_utils.py", line 63, in __http_request_json
    response = http.request(method, request_url, headers={}, params=params)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos/http.py", line 215, in request
    verify=verify, **kwargs)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos/util.py", line 586, in timer
    return fn(*args, **kwargs)
  File "/Users/benjamintrapani/.dcos/subcommands/kafka/env/lib/python2.7/site-packages/dcos/http.py", line 100, in _request
    raise DCOSException('URL [{0}] is unreachable: {1}'.format(url, e))
dcos.errors.DCOSException: URL [https://m1.dcos/service/kafka/v1/connection] is unreachable: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by tamarrow** [comment]
@BenjaminTrapani can you please repost this to https://github.com/mesosphere/dcos-kafka-service

**Comment by jsancio** [comment]
@gabrielhartmann Please take a look.

**Comment by tamarrow** [comment]
Closing, since this is opened under the kafka repo
