### ISSUE TITLE
task ls --completed fails

### ISSUE THREAD

**Issue by nickbp** [dcos/dcos-cli#771]
```
nick@augustao:~$ dcos task ls
===> siege.4f9b9ab9-80f1-11e6-ab75-225d308e1d52 <===
stderr  stderr.logrotate.conf  stdout  stdout.logrotate.conf
===> httpd.2f5b7a01-80ec-11e6-ab75-225d308e1d52 <===
stderr  stderr.logrotate.conf  stdout  stdout.1  stdout.2  stdout.3  stdout.4  stdout.5  stdout.6  stdout.7  stdout.8  stdout.9  stdout.logrotate.conf  stdout.logrotate.state

nick@augustao:~$ dcos task ls --completed
Traceback (most recent call last):
  File "cli/dcoscli/subcommand.py", line 99, in run_and_capture
  File "cli/dcoscli/task/main.py", line 18, in main
  File "cli/dcoscli/util.py", line 21, in wrapper
  File "cli/dcoscli/task/main.py", line 31, in _main
  File "dcos/cmds.py", line 43, in execute
  File "cli/dcoscli/task/main.py", line 197, in _ls
  File "dcos/mesos.py", line 718, in directory
TypeError: 'NoneType' object is not subscriptable

nick@augustao:~$ dcos --version
dcoscli.version=0.4.12
dcos.version=1.8-dev
dcos.commit=02e6c655efdafca6f3336d25f7e5344bf35f6ca6
dcos.bootstrap-id=c8b4c4578211a1608391b53ab0a30a5b044215aa
```

**Comment by jsancio** [comment]
It looks like the way we are parsing commands and routing to the handlers is incorrect:

```
$ env/bin/dcos task ls --json
I am in _task(ls, False, True)
[]
$ env/bin/dcos task ls --completed
I am in _ls(None, None, False, True)
Traceback (most recent call last):
  File "/home/jose/work/dcos-cli/cli/dcoscli/subcommand.py", line 99, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/home/jose/work/dcos-cli/cli/dcoscli/task/main.py", line 18, in main
    return _main(argv)
  File "/home/jose/work/dcos-cli/cli/dcoscli/util.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/jose/work/dcos-cli/cli/dcoscli/task/main.py", line 31, in _main
    return cmds.execute(_cmds(), args)
  File "/home/jose/work/dcos-cli/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/home/jose/work/dcos-cli/cli/dcoscli/task/main.py", line 201, in _ls
    dir_ = posixpath.join(task_obj.directory(), path)
  File "/home/jose/work/dcos-cli/dcos/mesos.py", line 718, in directory
    return self.executor()['directory']
TypeError: 'NoneType' object is not subscriptable
$ env/bin/dcos task ls --completed --json
I am in _task(ls, True, True)
[]
```

**Comment by jsancio** [comment]
cc @tamarrow @cruhland

**Comment by tamarrow** [comment]
@jsancio  `task ls --json` gets routed to `_task` because there is no `--json` option for `dcos task ls`. @nickbp can you provide steps to repro please?

**Comment by nickbp** [comment]
Seeing different issues now, looks like it's now requiring a task name (to list task names)?:

```
dcoscli.version=0.4.12
dcos.version=1.9-dev
dcos.commit=dbf5861e5f08d8a1c78fcdc4b4a31b6a52f88af0
dcos.bootstrap-id=399112261f82e73d10c01ba2975d4aab0e53d527
```

New Open cluster with 1 private node and 0 public nodes, with one package installed and then uninstalled:

```
$ dcos config set core.dcos_url http://nick-ug4z-elasticl-7n2418fhs4wz-2100777302.us-west-2.elb.amazonaws.com/
[core.dcos_url]: changed from 'http://nick-550i-elasticl-1vt80slzeytsk-1492650924.us-west-2.elb.amazonaws.com/' to 'http://nick-ug4z-elasticl-7n2418fhs4wz-2100777302.us-west-2.elb.amazonaws.com/'
$ dcos auth login

Please go to the following link in your browser:

    http://nick-ug4z-elasticl-7n2418fhs4wz-2100777302.us-west-2.elb.amazonaws.com/login?redirect_uri=urn:ietf:wg:oauth:2.0:oob

Enter authentication token: <TOKEN>
Login successful!
$ dcos package install cassandra
DC/OS Cassandra Service default configuration requires 3 nodes each with 1.5 CPU shares, 5376MB of memory and 11264MB of disk for running Cassandra Nodes. And, 1 node with 0.5 CPU shares, 2048MB of memory for running the service scheduler.
Continue installing? [yes/no] yes
Installing Marathon app for package [cassandra] version [1.0.16-3.0.8]
Installing CLI subcommand for package [cassandra] version [1.0.16-3.0.8]
New command available: dcos cassandra
DC/OS Apache Cassandra has been successfully installed!

	Documentation: https://docs.mesosphere.com/current/usage/service-guides/cassandra/
	Issues: https://dcosjira.atlassian.net/projects/CASSANDRA/issues
$ dcos package uninstall cassandra
Uninstalled package [cassandra] version [1.0.16-3.0.8]
DC/OS Apache Cassandra service has been uninstalled.
Please follow the instructions at https://docs.mesosphere.com/current/usage/service-guides/cassandra/uninstall to remove any persistent state.
$ dcos task ls --completed
._jre  jre  scheduler  scheduler.zip  server-jre-8u74-linux-x64.tar.gz  stderr  stderr.logrotate.conf  stdout  stdout.logrotate.conf
$ dcos task ls
Cannot find a task with ID containing ""
```

Same cluster config, with nothing installed:

```
$ dcos config set core.dcos_url http://nick-ygmk-elasticl-1ug5kze1pk08z-1686635435.us-west-2.elb.amazonaws.com/
d[core.dcos_url]: changed from 'http://nick-ug4z-elasticl-7n2418fhs4wz-2100777302.us-west-2.elb.amazonaws.com/' to 'http://nick-ygmk-elasticl-1ug5kze1pk08z-1686635435.us-west-2.elb.amazonaws.com/'
$ dcos auth login

Please go to the following link in your browser:

    http://nick-ygmk-elasticl-1ug5kze1pk08z-1686635435.us-west-2.elb.amazonaws.com/login?redirect_uri=urn:ietf:wg:oauth:2.0:oob

Enter authentication token: <TOKEN>
Login successful!
$ dcos task ls
Cannot find a task with ID containing ""
$ dcos task ls --completed
Cannot find a task with ID containing ""
```
