### ISSUE TITLE
install dcos cli: ImportError: cannot import name PIPE

### ISSUE THREAD

**Issue by navicore** [dcos/dcos-cli#774]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?  
Enterprise 1.7.2

If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

### What operating system and version are you using?
repro on OSX and Ubuntu 16.04

### What did you do?
If possible please provide a recipe for reproducing.
`install.sh`

### What did you expect to see?
dcos install

### What did you see instead?
```
dcos % bash install.sh /Users/navicore/dcos XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Installing DC/OS CLI from PyPI...

New python executable in /Users/navicore/dcos/bin/python2.7
Also creating executable in /Users/navicore/dcos/bin/python
Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/navicore/dcos/bin/dcos", line 7, in <module>
    from dcoscli.main import main
  File "/Users/navicore/dcos/lib/python2.7/site-packages/dcoscli/main.py", line 7, in <module>
    from dcos import config, constants, emitting, errors, http, subcommand, util
  File "/Users/navicore/dcos/lib/python2.7/site-packages/dcos/config.py", line 10, in <module>
    from dcos import constants, jsonitem, subcommand, util
  File "/Users/navicore/dcos/lib/python2.7/site-packages/dcos/subcommand.py", line 12, in <module>
    from subprocess import PIPE
ImportError: cannot import name PIPE
```

Unable to install the dcos cli on OSX.  getting the same error on Ubuntu:

```
~ % mkdir -p dcos && cd dcos &&
  curl -O https://downloads.mesosphere.com/dcos-cli/install-optout.sh &&
  bash ./install-optout.sh . XXXXXXXXXXXXXXXXXXXXXXXXXXXX &&
  source ./bin/env-setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5174  100  5174    0     0  25490      0 --:--:-- --:--:-- --:--:-- 25613
Installing DCOS CLI from PyPI...

New python executable in /home/navicore/dcos/bin/python
Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/navicore/dcos/bin/dcos", line 7, in <module>
    from dcoscli.main import main
  File "/home/navicore/dcos/local/lib/python2.7/site-packages/dcoscli/main.py", line 7, in <module>
    from dcos import config, constants, emitting, errors, http, subcommand, util
  File "/home/navicore/dcos/local/lib/python2.7/site-packages/dcos/config.py", line 10, in <module>
    from dcos import constants, jsonitem, subcommand, util
  File "/home/navicore/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py", line 12, in <module>
    from subprocess import PIPE
ImportError: cannot import name PIPE

dcos % uname -a
Linux pangea 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
dcos % which pip
/usr/local/bin/pip
dcos % pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
dcos % virtualenv --version
15.0.2
dcos %
```

**Comment by tamarrow** [comment]
@navicore can you please provide the python version and cli version? 

I would recommend using the CLI binary instead and not worry about dependencies. See: https://docs.mesosphere.com/1.8/usage/cli/install/ (And don't worry, this works for 1.7 clusters as well)

**Comment by navicore** [comment]
Python 2.7.12

unsure where to find the cli version, it is what ever https://downloads.mesosphere.com/dcos-cli/install-optout.sh serves.

trying the bin cli shortly, thx.

**Comment by TerryHowe** [comment]
https://github.com/dcos/dcos-cli/pull/790
