### ISSUE TITLE
subprocess module override conflicts with builtin subprocess Python module

### ISSUE THREAD

**Issue by adragomir** [dcos/dcos-cli#811]
Please answer the following questions before submitting your issue. Thanks!
### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

dcoscli.version=0.4.13
dcos.version=1.8.4
dcos.commit=e64024af95b62c632c90b9063ed06296fcf38ea5
dcos.bootstrap-id=5b4aa43610c57ee1d60b4aa0751a1fb75824c083
### What operating system and version are you using?

Mac OS X Mavericks
### What did you do?

dcos node ssh --master-proxy --leader
### What did you expect to see?

A working ssh login
### What did you see instead?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dcoscli/subcommand.py", line 99, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 28, in main
    return _main(argv)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/util.py", line 21, in wrapper
    result = func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 50, in _main
    return cmds.execute(_cmds(), args)
  File "/usr/local/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 589, in _ssh
    return subprocess.Subproc().call(cmd, shell=True)
  File "/usr/local/lib/python2.7/site-packages/dcos/subprocess.py", line 62, in call
    return subprocess.call(

At closer investigation it looks like in the call method in dcos/subprocess.py, the subprocess module contents (listed with dir) are actually the ones in the file, not the ones in the builtin subprocess module

**Comment by tamarrow** [comment]
@adragomir thanks for the report. Can you please paste the output of `dcos --log-level=debug node ssh --master-proxy --leader`

**Comment by adragomir** [comment]
@tamarrow here you go (I replaced the Output DC/OS url with REDACTED, the first ip with REDACTED_IP1, and the second ip with REDACTED_IP2):

More information: Using Mac OS X Mavericks, with Python 2.7.10, installed from brew, no venv

```
❯ dcos --log-level=debug node ssh --master-proxy --leader
MainThread: 2016-10-17 22:02:11,367 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:87 - Sending HTTP ['get'] to [u'http://REDACTED/mesos_dns/v1/hosts/leader.mesos.']: {}
MainThread: 2016-10-17 22:02:11,854 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:214 - Starting new HTTP connection (1): REDACTED
MainThread: 2016-10-17 22:02:12,379 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:401 - "GET /mesos_dns/v1/hosts/leader.mesos. HTTP/1.1" 401 363
MainThread: 2016-10-17 22:02:12,385 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:117 - Received HTTP response [401]: {'Content-Length': '363', 'Via': '1.1 wsg.Bucharest', 'Age': '1', 'Server': 'openresty/1.9.15.1', 'Date': 'Mon, 17 Oct 2016 19:02:12 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'WWW-Authenticate': 'oauthjwt'}
MainThread: 2016-10-17 22:02:12,386 /usr/local/lib/python2.7/site-packages/dcos/util.py:timer:485 - duration: dcos.http._request: 1.02s
MainThread: 2016-10-17 22:02:12,387 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:87 - Sending HTTP ['get'] to [u'http://REDACTED/mesos_dns/v1/hosts/leader.mesos.']: {}
MainThread: 2016-10-17 22:02:12,389 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:214 - Starting new HTTP connection (1): REDACTED
MainThread: 2016-10-17 22:02:12,562 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:401 - "GET /mesos_dns/v1/hosts/leader.mesos. HTTP/1.1" 200 65
MainThread: 2016-10-17 22:02:12,563 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:117 - Received HTTP response [200]: {'Content-Length': '65', 'Via': '1.1 wsg.Bucharest', 'Age': '0', 'Server': 'openresty/1.9.15.1', 'Date': 'Mon, 17 Oct 2016 19:02:12 GMT', 'Content-Type': 'application/json'}
MainThread: 2016-10-17 22:02:12,563 /usr/local/lib/python2.7/site-packages/dcos/util.py:timer:485 - duration: dcos.http._request: 0.18s
MainThread: 2016-10-17 22:02:12,564 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:87 - Sending HTTP ['get'] to [u'http://REDACTED/metadata']: {'Accept': 'application/json'}
MainThread: 2016-10-17 22:02:12,566 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:214 - Starting new HTTP connection (1): REDACTED
MainThread: 2016-10-17 22:02:12,925 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:401 - "GET /metadata HTTP/1.1" 401 363
MainThread: 2016-10-17 22:02:12,931 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:117 - Received HTTP response [401]: {'Content-Length': '363', 'Via': '1.1 wsg.Bucharest', 'Age': '0', 'Server': 'openresty/1.9.15.1', 'Date': 'Mon, 17 Oct 2016 19:02:12 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'WWW-Authenticate': 'oauthjwt'}
MainThread: 2016-10-17 22:02:12,931 /usr/local/lib/python2.7/site-packages/dcos/util.py:timer:485 - duration: dcos.http._request: 0.37s
MainThread: 2016-10-17 22:02:12,931 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:87 - Sending HTTP ['get'] to [u'http://REDACTED/metadata']: {'Accept': 'application/json'}
MainThread: 2016-10-17 22:02:12,933 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:214 - Starting new HTTP connection (1): REDACTED
MainThread: 2016-10-17 22:02:13,107 /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:401 - "GET /metadata HTTP/1.1" 200 87
MainThread: 2016-10-17 22:02:13,113 /usr/local/lib/python2.7/site-packages/dcos/http.py:_request:117 - Received HTTP response [200]: {'Content-Length': '87', 'Via': '1.1 wsg.Bucharest', 'Age': '0', 'Server': 'openresty/1.9.15.1', 'Date': 'Mon, 17 Oct 2016 19:02:13 GMT', 'Content-Type': 'application/json'}
MainThread: 2016-10-17 22:02:13,114 /usr/local/lib/python2.7/site-packages/dcos/util.py:timer:485 - duration: dcos.http._request: 0.18s
Running `ssh -A -t core@REDACTED_IP1 ssh -A -t core@REDACTED_IP2 `
['/usr/local/bin', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/adr/Library/Python/2.7/lib/python/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/opt/llvm/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0', '/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg', '/Library/Python/2.7/site-packages']
------------
['Subproc', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'os', 'subprocess']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dcoscli/subcommand.py", line 99, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 28, in main
    return _main(argv)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/util.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 50, in _main
    return cmds.execute(_cmds(), args)
  File "/usr/local/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/usr/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 589, in _ssh
    return subprocess.Subproc().call(cmd, shell=True)
  File "/usr/local/lib/python2.7/site-packages/dcos/subprocess.py", line 62, in call
    return subprocess.call(
AttributeError: 'module' object has no attribute 'call'
```

**Comment by tamarrow** [comment]
@adragomir thanks. I will take a look. Do you also see this error when you use the binary CLI? https://docs.mesosphere.com/1.8/usage/cli/install/

**Comment by adragomir** [comment]
@tamarrow it does not happen with the packaged binary CLI.

**Comment by tamarrow** [comment]
Glad it worked! Yes, it's a python2 bug. We are dropping support for it so we can use python3 features, and we have the binaries so versions shouldn't matter to users :)
