### ISSUE TITLE
When trying to SSH into my cluster i get an AttributeError: 'module' object has no attribute 'call'

### ISSUE THREAD

**Issue by robvanpamel** [dcos/dcos-cli#814]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

### What operating system and version are you using?
```
rvpamel@SAG-PC-32 ~/dcos/dcos/bin $ dcos --version
dcoscli.version=0.4.14
dcos.version=1.7-open
dcos.commit=14509fe1e7899f439527fb39867194c7a425c771
dcos.bootstrap-id=3a2b7e03c45cd615da8dfb1b103943894652cd71
```
### What did you do?
If possible please provide a recipe for reproducing.
rvpamel@SAG-PC-32 ~/dcos/dcos/bin $ dcos node ssh --master-proxy --mesos-id=a02d750a-db3c-425a-8248-007881f36ead-S2

### What did you expect to see?

i'm able to SSH into my node.

### What did you see instead?

```

Running `ssh -A -t core@54.198.49.129 ssh -A -t core@10.0.3.181 `
Traceback (most recent call last):
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcoscli/subcommand.py", line 99, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 29, in main
    return _main(argv)
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcoscli/util.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 51, in _main
    return cmds.execute(_cmds(), args)
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 590, in _ssh
    return subprocess.Subproc().call(cmd, shell=True)
  File "/home/rvpamel/dcos/local/lib/python2.7/site-packages/dcos/subprocess.py", line 58, in call
    return subprocess.call(
AttributeError: 'module' object has no attribute 'call'

```

**Comment by cruhland** [comment]
@tamarrow this looks related to #790 and #774.

@robvanpamel I'd try @tamarrow's recommendation from #774:
> I would recommend using the CLI binary instead and not worry about dependencies. See: https://docs.mesosphere.com/1.8/usage/cli/install/ (And don't worry, this works for 1.7 clusters as well)

**Comment by tamarrow** [comment]
This is a duplicate, closing
