### ISSUE TITLE
dcos package search without search term throws error

### ISSUE THREAD

**Issue by mattwoolnough** [dcos/dcos-cli#911]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
dcoscli.version=0.4.15
dcos.version=1.8.8
### What operating system and version are you using?
Windows 10

### What did you do?
If possible please provide a recipe for reproducing.

dcos package search

### What did you expect to see?

No result or statement to the effect of "please enter search term".

### What did you see instead?
Traceback (most recent call last):
  File "dcoscli\subcommand.py", line 101, in run_and_capture
  File "dcoscli\package\main.py", line 22, in main
  File "dcoscli\util.py", line 22, in wrapper
  File "dcoscli\package\main.py", line 36, in _main
  File "dcos\cmds.py", line 43, in execute
  File "dcoscli\package\main.py", line 471, in _search
  File "dcos\emitting.py", line 118, in publish_table
  File "dcos\emitting.py", line 59, in publish
  File "dcos\emitting.py", line 76, in print_handler
  File "dcos\emitting.py", line 157, in _page
  File "c:\python35\lib\encodings\cp850.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 10400: character maps to <undefined>

**Comment by tamarrow** [comment]
Does your windows machine support utf-8 encoding?
